environment:
  ANDROID_HOME: "C:\\android-sdk-windows"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

clone_folder: "C:\\projects\\android-gradle-java-app-template"

init:
  - cd \
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip
  - 7z x sdk-tools-windows-3859397.zip > nul
  - cd C:\projects\android-gradle-java-app-template


build_script:
  - gradlew.bat clean assembleDebugAndroidTest testDebug -Pci -Dscan --stacktrace

artifacts:
  - path: "build\\reports\\"

cache:
  - "%USERPROFILE%\\.m2"
  - "%USERPROFILE%\\.gradle"
